### ISSUE TITLE
Create a Subscription Management Dashboard

### ISSUE THREAD

**Issue by YAkshTOyesh** [YAkshTOyesh/Forecast_Alchemist#10]
## Description
This issue is to allow flexibility in the service provided. Essential for a high quality marketable product.

**Tasks**
- [ ] Allow users to manage their subscriptions (upgrade, downgrade, cancel).
- [ ] Write unit tests to ensure dashboard functionality works properly.
- [ ] Allow for orchestration of LLMs
- [ ] BONUS: Personal Database and info collection???

**Notes**
Linking payments to orchestration models only and subscription management
