### ISSUE TITLE
Add Error Handling

### ISSUE THREAD

**Issue by YAkshTOyesh** [YAkshTOyesh/Forecast_Alchemist#12]
## Description

**Tasks**

- [ ] Do Research
- [ ] Create failure case scenarios
- [ ] Implement global error handling on both frontend and backend.
- [ ]Test error handling scenarios, such as invalid SQL inputs or payment failures.

**Notes**
This is the error proofing stage.
