### ISSUE TITLE
Set Up Python API

### ISSUE THREAD

**Issue by YAkshTOyesh** [YAkshTOyesh/Forecast_Alchemist#2]
## Description
Set up the virtual environment for Python to develop LangChain and LLM Model API.

**Tasks**

- [ ] Create a Python service in the backend folder with an API endpoint to handle requests from the frontend.
- [ ] Test a simple API request.
- [ ] Add Logging
- [ ] BONUS: Implement LangChain
- [ ] BONUS:  UnitTest a simple LangChain response

**Notes**
Read on REST API or Fast API, venv, LangChain documentation
