### ISSUE TITLE
Implement SQL Agent API - Backend

### ISSUE THREAD

**Issue by YAkshTOyesh** [YAkshTOyesh/Forecast_Alchemist#3]

**Comment by YAkshTOyesh** [comment]
## Description

**Tasks**

- [ ] Create a simple form in NextJS for input 
- [ ] Build a microservice Fast API
- [ ] API accepts natural language input
- [ ] Returns SQL Query with LangChain and OpenAI
- [ ] Add Logging
- [ ] Unit testing for SQL generation 

**Notes**
Do not focus on frontend. Backend is important here.
