### ISSUE TITLE
Implement Chat Frontend

### ISSUE THREAD

**Issue by YAkshTOyesh** [YAkshTOyesh/Forecast_Alchemist#4]
## Description

**Tasks**

- [ ] Implement beautiful frontend with Claude AI and ShadCN library
- [ ] Implement chat interface
- [ ] Use TypeScript, Zod and Tailwind CSS for type safety and validation
- [ ] Implement efficient logging
- [ ]  Integration test Routing flow from frontend and backend

**Notes**
This will be our beautiful basic website with a single core functionality. No home page for now.
