### ISSUE TITLE
Implement Auth.js for User Authentication

### ISSUE THREAD

**Issue by YAkshTOyesh** [YAkshTOyesh/Forecast_Alchemist#5]
## Description

**Tasks**

- [ ] Set up user sign-up, login, and logout flows using Auth.js.
- [ ] Beautiful frontend
- [ ] Set up a homepage
- [ ] No access unless signed-in or authorized.
- [ ] BONUS: Add Beloit College
- [ ] BONUS: Add Guest sign-in option.
- [ ] BONUS: Integrate with Beloit.edu Google sign in
- [ ] Write unit tests to ensure that authentication logic works properly.
- [ ] Ensure proper logging files

**Notes**
This is the frontend part of the security
